config/routes.rb
Doorsnwindows::Application.routes.draw do

  resources :leads
  resources :landing_leads
  resources :users
  resources :activities
  resources :sessions, only: [:new, :create, :destroy]
  resources :inquiries, only: [:new, :create]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/thank_you',           to: 'static_pages#redirect_thank_you',  via: 'get'
  match '/no_service',          to: 'static_pages#redirect_no_service', via: 'get'

  match '/about_us/story',      to: 'static_pages#about_story',         via: 'get'
  # match '/about_us/services',   to: 'static_pages#about_services',      via: 'get'
  match '/about_us/guarantee',  to: 'static_pages#about_guarantee',     via: 'get'
  match '/products/windows',    to: 'static_pages#products_windows',    via: 'get'
  match '/products/doors',      to: 'static_pages#products_doors',      via: 'get'
  match '/products/hardware',   to: 'static_pages#products_hardware',   via: 'get'
  # match '/manufacturers/choosing',to: 'static_pages#mfg_choose',        via: 'get'
  match '/info/how',            to: 'static_pages#info_how',            via: 'get'
  match '/info/faqs',           to: 'static_pages#info_faqs',           via: 'get'
  # match '/info/installs',       to: 'static_pages#info_installs',       via: 'get'
  # match '/info/mfgs',           to: 'static_pages#info_mfgs',           via: 'get'
  # match '/info/historic',       to: 'static_pages#info_historic',       via: 'get'

  match '/contact/email',       to: 'static_pages#contact_email',   via: 'get'
  match '/contact/info',        to: 'static_pages#contact_info',    via: 'get'

  match '/savings',             to: 'landing_leads#savings',        via: 'get'
  # match '/savings/windows',     to: 'landing_leads#windows',        via: 'get'

  root to: 'static_pages#home'

  #sidekiq
  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @lead = Lead.new
  end

  def redirect_thank_you
    render 'static_pages/redirects/thank_you'
  end

  def redirect_no_service
    render 'static_pages/redirects/no_service'
  end

  def about_story
    render 'static_pages/about_us/about'
  end

  def about_services
    render 'static_pages/about_us/services'
  end

  def about_guarantee
    render 'static_pages/about_us/guarantee'
  end

  def products_windows
    render 'static_pages/products/windows'
  end

  def products_doors
    render 'static_pages/products/doors'
  end

  def products_hardware
    render 'static_pages/products/hardware'
  end

  def mfg_choose
    render 'static_pages/mfgs/choose'
  end

  def info_how
    render 'static_pages/info/how'
  end

  def info_faqs
    render 'static_pages/info/faqs'
  end

  def info_installs
    render 'static_pages/info/installs'
  end

  def info_mfgs
    render 'static_pages/info/mfgs'
  end

  def info_historic
    render 'static_pages/info/historic'
  end

  def contact_email
    @inquiry = Inquiry.new
    render 'static_pages/contact/email_us'
  end

  def contact_info
    render 'static_pages/contact/info'
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_us/about.html.haml
- provide(:title, 'About')

#page-title
  %h1 The DoorsNWindows Story
.row-fluid.overflow-hidden{style: "height: 1448px;"}
  .span3.full-height.visible-desktop
    .widget-alt.full-height
      .well{data:{spy:"affix", offset:{top:"0"}}}
        .headline Sections
        %ul.nav.nav-list.links-list-alt
          %li
            %a{href: "#started"}
              How It Started
              %i.fa.fa-chevron-right.pull-right
          %li
            %a{href: "#values"}
              Core Values
              %i.fa.fa-chevron-right.pull-right
          %li
            %a{href: "#difference"}
              The DNW Difference
              %i.fa.fa-chevron-right.pull-right
  .span9
    #started.clearfix
      .headline
        %h3 How we got started
      :markdown
        #### *A family-owned operation*

      %img{class: "thumbnail pull-right", src:"#{image_url('logo_color_white.jpg')}", style:"max-width:400px;"}

      :markdown
        We are a small, family-owned and operated window and door company.
        Company founder Louis Ottrando and his wife Christine entered the
        home replacement industry in 1985 and have been committed to great
        service ever since.

        Our expertise comes from being actual installers who know precisely
        what's involved in an installation job. Having been in the window
        and door industry for our entire professional career, we have seen
        and adapted to the many changes in this industry. We are a small
        company with no intention of growing much larger; we want to keep
        things less complicated. We have been blessed doing a trade and
        offering a service we truly enjoy and we do not sub-out our window
        installations.

        If you choose to work with DoorsNWindows, you will notice our
        professionalism and experience. We are not interested in pressuring
        you into a purchase that you neither want nor need. Our aim is to
        make it easy for you to replace your doors and windows and help you
        save money in the process. Since we are a small company, you will
        not have the commission mark-up of a typical sales-team.  We run a
        no-pressure, homeowner-oriented business.

        Unlike most door and window companies, we will install most products*
        customers have bought from large warehouse stores and will pick up,
        deliver, and install their products.

        ###### *Please call for a price and to verify that we will install the product you have purchased.

    #values.clearfix
      .headline
        %h3 Our core values
      :markdown
        #### *Help and expertise, without all the pressure*

      .thumbnail.pull-left
        = image_tag 'company/packing-house-1.jpg'
        .caption
          :markdown
            ##### Our beautiful new showroom in the historical downtown Claremont Packing House is located upstairs just above Z-Pizza.

      :markdown
        We do not like playing salesman games. We only make our
        money on the installation aspect and give you the best
        price available on the product. We do not sell product
        without our installation. We save our customers an enormous
        amount of money. In fact we install many products customers
        have bought from stores and we will go pick up and deliver
        and install their product.

        Customers will not speak to inexperienced salespeople but
        to people that can help answer their questions. We will
        gladly compete against our competitors for your business
        and go over any differences for you to make an educated
        investment.

        We have a beautiful new location in the historical downtown
        Claremont Packing House: 532 W First St., Suite #202 Claremont,
        CA 91711. Located upstairs above Z-Pizza.  Our showroom is by
        appointment only. Please call beforehand to set-up an appointment.
        (909)912-8510. We have a small assortment of window styles located
        in our showroom.

    #difference.clearfix
      .headline
        %h3 The DoorsNWindows difference

      .row-fluid
        .span7
          .pricing-table
            .color-1
              %h3 We go above and beyond the competition
              %h4.center The best service at the lowest prices anywhere
              %ul.unstyled
                %li
                  %i.fa.fa-phone
                  You will only speak with knowlegable representatives
                %li
                  %i.fa.fa-ban
                  We refuse to use high pressure sales with you
                %li
                  %i.fa.fa-thumbs-o-up
                  Products from any manufacturer or store of your choice
                %li
                  %i.fa.fa-road
                  Our install crew has 29 years of experience in quality
                %li
                  %i.fa.fa-star
                  We only use the best materials and the best techniques
                %li
                  %i.fa.fa-certificate
                  We offer a 5-year warranty on all our installations
              %h4.center.sign-up
                See for yourself:
                = link_to "Free Quote", savings_path, :class => "btn btn-majoo"
        .span5
          %img{class: "thumbnail pull-right", src:"#{image_url('milgard/tuscany-b.jpg')}", style:'height:380px'}

app/views/static_pages/about_us/guarantee.html.haml
- provide(:title, 'Guarantee')

#page-title
  %h1 DoorsNWindows 100% Guarantee

.row-fluid
  .span8
    .headline
      %h4 We guarantee our quality and services to all customers
    :markdown
      Our assurance to our customers- we are persuaded to do things
      correctly and we stand behind our installations. By law we are
      required to give a one-year warranty on our installations, but
      we automatically give a five-year warranty. We do offer extended
      warranties with our service plan for an additional fee. The
      service plan we offer is, every four months we will do a product
      checkup and cleaning which will keep your product in mint
      condition. If products are not serviced, your warranties can
      potentially be void. So whether you have our service plan or not,
      you should upkeep your product so warranties are not voided.

  .span4
    .headline
      %h4 The DoorsNWindows promise
    %img{class: "thumbnail", src:"#{image_url('istockphoto/guarantee.jpg')}"}

app/views/static_pages/about_us/services.html.haml
- provide(:title, 'Services')

#page-title
  %h1 DoorsNWindows Services
.row-fluid.overflow-hidden{style: "height: 1990px;"}
  .span3.full-height.visible-desktop
    .widget-alt.full-height
      .well{data:{spy:"affix", offset:{top:"0"}}}
        .headline Sections
        %ul.nav.nav-list.links-list-alt
          %li
            %a{href: "#estimates"}
              Consultations
              %i.fa.fa-chevron-right.pull-right
          %li
            %a{href: "#products"}
              Product Specialists
              %i.fa.fa-chevron-right.pull-right
          %li
            %a{href: "#installations"}
              Installations
              %i.fa.fa-chevron-right.pull-right
          %li
            %a{href: "#maintenance"}
              Maintenance
              %i.fa.fa-chevron-right.pull-right
  .span9
    #estimates.clearfix
      .headline
        %h3 Estimates & Consultations
      :markdown
        #### *All the information you need to plan your home renovations*

      %img{class: "thumbnail pull-left", src:"#{image_url('istockphoto/measure.jpg')}"}

      :markdown
        DoorsNWindows has always been a family owned & run operation.
        My wife and I have been together since high school,
        And we just celebrated our 25th anniversary.
        We have been together for 29 years, and when I became
        a window and door specialty license contractor three years
        before we got married, we've worked together since.
        We both handled different aspects of the job.

        Our expertise comes from being actual installers that knows
        precisely what's involved in a job. We have never had a career
        in anything else but the window and door industry and we have
        seen many things change. We are a small company and really
        do not have any intention on being large. We want to keep
        things less complicated. We are blessed with a beautiful
        daughter 13 years old and committed to homeschooling her.

        We have been blessed doing a trade and offering a service
        we truly enjoy.

        #### *Tough times*

        We went through some very testing time losing a lot of money
        and even our home during the housing bubble. We literally had
        material for 10 homes and had completed multiple jobs where
        customers had just abandoned their homes. This left us at major
        loss. We thank God for his strength and pulling us through
        those times. We remain obligated and committed to our customers
        through all of this. This is why we still have a good name.

    #products.clearfix
      .headline
        %h3 Product and Manufacturer Specialists
      :markdown
        #### *We have expert knowledge on all of the popular products & manufacturers*

      .row-fluid
        .span2.h200
          %img{class: "thumbnail vert-align", src:"#{image_url('logos/aaw.png')}"}
        .span2.h200
          %img{class: "thumbnail vert-align", src:"#{image_url('logos/atrium.jpg')}"}
        .span2.h200
          %img{class: "thumbnail", src:"#{image_url('logos/escon.jpg')}"}
        .span2.h200
          %img{class: "thumbnail vert-align", src:"#{image_url('logos/milgard.jpg')}"}
        .span2.h200
          %img{class: "thumbnail", src:"#{image_url('logos/pella.jpg')}"}
        .span2.h200
          %img{class: "thumbnail vert-align", src:"#{image_url('logos/superior.jpg')}"}

      :markdown
        We do not like playing salesman games. We only make our
        money on the installation aspect and give you the best
        price available on the product. We do not sell product
        without our installation. We save our customers an enormous
        amount of money. In fact we install many products customers
        have bought from stores and we will go pick up and deliver
        and install their product.

        Customers will not speak to inexperienced salespeople but
        to people that can help answer their questions. We will
        gladly compete against our competitors for your business
        and go over any differences for you to make an educated
        investment.

        We are not a large company with salespeople nor do we want
        to be. We have done it before and there is a loss of quality.
        In order to serve our customers efficiently and cut costs.
        We depend heavily on keeping our overhead low. We do not have
        physical showrooms that takes up money and man-hours that
        would add to the customer's cost.

    #installations.clearfix
      .headline
        %h3 High Quality Installations

      %img{class: "thumbnail pull-right", src:"#{image_url('istockphoto/expert2.jpg')}"}

      :markdown
        #### *We are able to put just about any type of product in your home.*

        1. It really starts off with an accurate assessment and measurement of each opening.
        2. We will remove any window treatments within the wall condition.
        3. Clear out the opening removing sashes, stop etc.
        4. We use the strongest the poly urethane sealant that will put behind the back of all window fin.
        There are slight variations depending on the type of window application.
        5. Windows are fastened with galvanize three-inch screws and squared into opening.
        6. We will then inject a foam between any area or gap between the new frame and the old.
        This will harden strengthening your window frame making it more rigid. It will also help with installation.
        7. We will then trim around the perimeter of your window with a matching vinyl in most cases around the inside.
        8. Your home will be Clean throughout the whole process and protected.
        9. We will walk the job and verify everything as been done properly. If there are any manufactured
        defect in the product not due to installation. Manufactures warranty and service will handle this
        directly with the customer to schedule anything that needs to be serviced or replaced. Payment for
        installation must still be paid if it is a manufactured issue. If we for some reason receive merchandise
        that cannot be installed due to the manufacture. These items may be deducted from your installation payment
        with the balance being paid on completion.

    #maintenance.clearfix
      .headline
        %h3 Maintenance Plans & Packages

      .row-fluid
        .span7
          .pricing-table
            .color-1
              %h3 We go above and beyond the competition
              %h4.center The best service at the lowest prices anywhere
              %ul.unstyled
                %li
                  %i.fa.fa-phone
                  You will only speak with knowlegable representatives
                %li
                  %i.fa.fa-ban
                  We refuse to use high pressure sales with you
                %li
                  %i.fa.fa-thumbs-o-up
                  Products from any manufacturer or store of your choice
                %li
                  %i.fa.fa-road
                  Our install crew has 29 years of experience in quality
                %li
                  %i.fa.fa-star
                  We only use the best materials and the best techniques
                %li
                  %i.fa.fa-certificate
                  We offer a 5-year warranty on all our installations
              %h4.center.sign-up
                See for yourself:
                = link_to "Get a Free Quote today!", savings_path
        .span5
          %img{class: "thumbnail", src:"#{image_url('company/cup.jpg')}"}