config/routes.rb
Doorsnwindows::Application.routes.draw do

  resources :leads
  resources :landing_leads
  resources :users
  resources :activities
  resources :sessions, only: [:new, :create, :destroy]
  resources :inquiries, only: [:new, :create]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/thank_you',           to: 'static_pages#redirect_thank_you',  via: 'get'
  match '/no_service',          to: 'static_pages#redirect_no_service', via: 'get'

  match '/about_us/story',      to: 'static_pages#about_story',         via: 'get'
  # match '/about_us/services',   to: 'static_pages#about_services',      via: 'get'
  match '/about_us/guarantee',  to: 'static_pages#about_guarantee',     via: 'get'
  match '/products/windows',    to: 'static_pages#products_windows',    via: 'get'
  match '/products/doors',      to: 'static_pages#products_doors',      via: 'get'
  match '/products/hardware',   to: 'static_pages#products_hardware',   via: 'get'
  # match '/manufacturers/choosing',to: 'static_pages#mfg_choose',        via: 'get'
  match '/info/how',            to: 'static_pages#info_how',            via: 'get'
  match '/info/faqs',           to: 'static_pages#info_faqs',           via: 'get'
  # match '/info/installs',       to: 'static_pages#info_installs',       via: 'get'
  # match '/info/mfgs',           to: 'static_pages#info_mfgs',           via: 'get'
  # match '/info/historic',       to: 'static_pages#info_historic',       via: 'get'

  match '/contact/email',       to: 'static_pages#contact_email',   via: 'get'
  match '/contact/info',        to: 'static_pages#contact_info',    via: 'get'

  match '/savings',             to: 'landing_leads#savings',        via: 'get'
  # match '/savings/windows',     to: 'landing_leads#windows',        via: 'get'

  root to: 'static_pages#home'

  #sidekiq
  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  include PublicActivity::Model
  include LeadsHelper

  before_save do
    self.name = name.titleize
    self.phone = phone.gsub(/[^0-9]/i, '')
    self.email = email.downcase
    self.zip = zip.gsub(/[^0-9]/i, '')
  end

  #will_paginate
  self.per_page = 12

  VALID_PHONE_REGEX = /\A\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_ZIP_REGEX   = /\A\d{5}\z/

  validates :name, :phone, :email, :zip, :interest, :status, presence: true, allow_blank: false
  validates :name,  length: { maximum: 50 }
  validates :phone, format: { with: VALID_PHONE_REGEX }
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :zip,   format: { with: VALID_ZIP_REGEX }, length: { maximum: 5 }
  validates_inclusion_of :interest, :in => :lead_interests
  validates_inclusion_of :status, :in => :lead_status_options

  #geocoder
  geocoded_by :zip

  def self.search(search, type=nil)
    if type
      fields = type+' ilike :q'
    else
      types = %w(name email phone zip status)
      arr = []
      types.each do |t|
        arr << t+' ilike :q'
      end
      fields = arr.join(' or ')
    end

    if search
      where(fields, q: "%#{search}%")
    else
      all
    end
  end

  def self.center_point
    [33.969732,-117.89976]
  end

  def log!
    Log.create! :start_time => Time.now, :finish_time => Time.now, :message => self.errors.full_messages.to_s, :success => "N" if self.errors.count > 0
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :update, :destroy]
  before_action :delete_activity, only: [:destroy]

  def index
    @leads = Lead.reorder(sort_column + " " + sort_direction).paginate(page: params[:page]).search(params[:search], params[:type])
    fresh_when last_modified: @leads.maximum(:updated_at)
    expires_in 5.minutes
  end

  def show
    @lead = Lead.find(params[:id])
    @activities = @lead.activities.paginate(page: params[:page])
    fresh_when @lead, public: true
    expires_in 5.minutes
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)

    if @lead.valid?
      if @lead.geocode && @lead.distance_from(Lead.center_point) < 40
        @lead.save
        MailerWorker.perform_async(@lead.id)
        if signed_in?
          @lead.create_activity :create, owner: current_user, params: @lead.attributes
          flash[:success] = "#{ current_user.name } successfully created a lead."
          redirect_to leads_path
        else
          @lead.create_activity :new, params: @lead.attributes
          redirect_to thank_you_path
        end
      else
        redirect_to no_service_path
      end
    else #error rerouting
      render :errors
    end
  end

  def update
    @lead = Lead.find(params[:id])
    @lead.assign_attributes(lead_params)
    changes = @lead.changes

    respond_to do |format|
      if @lead.save
        @lead.create_activity :update, owner: current_user, params: changes unless changes.empty?
        format.html { render action: "index" }
        format.js   {}
        format.json { render json: @lead, status: :updated, location: @lead }
      else
        format_error(format, @lead)
      end
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @id = @lead.id
    @name = @lead.name

    respond_to do |format|
      if @lead.destroy
        format.html { render action: "index" }
        format.js   {}
        format.json { render json: @lead, status: :deleted, location: @lead }
      else
        format_error(format, @lead)
      end
    end
  end


  private
    def lead_params
      params.require(:lead).permit(:name, :phone, :email, :zip,
                                   :interest, :status, :notes)
    end

    def delete_activity
      @lead = Lead.find(params[:id])
      @lead.create_activity :delete, owner: current_user, params: @lead.attributes
    end

    def format_error(f, v)
      f.html { render action: "index" }
      f.js   {}
      f.json { render json: v.errors, status: :unprocessable_entity }
    end
end

app/helpers/leads_helper.rb
module LeadsHelper

  def lead_interests
    ['Doors', 'Windows', 'Both']
  end

  def lead_status_options
    ['New Lead',
     'Voicemail Left',
     'Non-Responsive',
     'Appointment Set',
     'Job Sold']
  end

  def lead_status_link(status)
    count = Lead.where(status: status).count

    if count > 0
      link_to count, params.merge(:search => status, :type => "status")
    else
      ''
    end
  end

  def lead_badge(text, css_class)
    css_class = 'badge lead-' + css_class.downcase.gsub(' ', '-')
    content_tag(:span, text, :class => css_class).html_safe
  end

  def lead_staleness(lead)
    css_class = ""
    if lead.status == "New Lead"
      css_class = lead.created_at < 1.day.ago ? "error" : "warning"
    end
    return css_class
  end

  def phone_format(phone)
    formatted = '(' +
    phone[0..2] + ') ' +
    phone[3..5] + '-' +
    phone[6..9]
    formatted
  end
end

app/views/leads/_form.html.haml
= simple_form_for(@lead, :html => { :honeypot => true, :class => 'form-horizontal pull-right' }) do |f|
  = f.error_notification

  = f.input :name, placeholder: 'First Last', input_html: { pattern: "[a-zA-Z-. ]+" }
  = f.input :phone, placeholder: '123-456-7890', input_html: { pattern: "[(]?[0-9]{3}[)]?[-. ]?[0-9]{3}[-. ]?[0-9]{4}" }
  = f.input :email, placeholder: 'user@example.com'
  = f.input :zip, placeholder: '12345', input_html: { pattern: "[0-9]{5}" }
  = f.input :interest, :label => "Interested in:", :collection => lead_interests, :as => :radio_buttons, :item_wrapper_class => 'inline'
  = f.input :status, :as => :hidden, :input_html => { :value => "New Lead" }

  = f.button :submit, "Free Quote", :class => 'btn-large btn-majoo pull-right'

app/views/leads/_instructions.html.haml
#slides
  .row
    %ul.paging
      .slide-btn
        .span2.offset2
          %li
            %a#sweepstake.feature-tab{href: "#0"}
              %i 1
        .span2
          %li
            %a#dashboard.feature-tab{href: "#1"}
              %i 2
        .span2
          %li
            %a#responsive.feature-tab{href: "#2"}
              %i 3
        .span2
          %li
            %a#cloud.feature-tab{href: "#3"}
              %i 4
  .feature-content.slides_container
    #sweepstake-content.slide-content{style: "display:block"}
      .row
        .span4
          = image_tag "2.jpg", align: "right"
        .span8
          %h2 1. One of our representatives will call you
          %p
            We have received your information, and the first available DoorsNWindows representative will call you with the phone number you provided.
            Our average call time after receiving your request is about 30 minutes.
            Once we touch base with you, we'll proceed to the next step: setting an appointment.
          %ul.unstyled.icons
            %li
              %i.icon-ok
              Live Calls
            %li
              %i.icon-ok
              Email Support
            %li
              %i.icon-ok
              Forums
            %li
              %i.icon-ok
              Other
    #dashboard-content.slide-content
      .row
        .span4
          = image_tag "4.jpg", align: "right"
        .span8
          %h2 2. We'll set an Appointment that works for your schedule
          %p
            DoorsNWindows has flexible scheduling options.
            We can often schedule new clients for same- or next-day appointments.
            Estimators are available for appointments Monday - Saturday, 9am - 5pm.
          %ul.icons.unstyled
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
    #responsive-content.slide-content
      .row
        .span4
          = image_tag "3.jpg", align: "right"
        .span8
          %h2 3. Our Estimator will come to your house for the Appointment
          %p
            Once the Estimator arrives, they will ask you to show them the doors or windows you want a quote for.
            The Estimator will then measure each window or door we are quoting for you.
            Measurements take 15-30 minutes on average, depending on the size of your home or project.
            Feel free to ask our Estimator any questions you may have; we can often answer clients' questions regarding their home or project on-site.

          %ul.icons.unstyled
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
            %li
              %i.icon-ok
              feature 1
    #cloud-content.slide-content
      .row
        .span4
          = image_tag "1_1.png", align: "right"
        .span8
          %h2 4. We'll email you your custom Quote within 24 hours
          %p
            No hassle, no confusion: just simple, straightforward pricing and details.
            DoorsNWindows Price Guarantee is: we will match or beat any competitor in price.
            Our core value is, we do not use sales pressure.
            We are not pushy with our clients.
            And we will always keep your quote on file, if you decide to move forward at a later date.

          %ul.icons.unstyled
            %li
              %i.icon-cloud
              feature 1
            %li
              %i.icon-cloud
              feature 1
            %li
              %i.icon-cloud
              feature 1
            %li
              %i.icon-cloud
              feature 1

app/views/leads/_lead.html.haml
%li
  .row-fluid
    .span2 Name: #{ lead.name }
    .span2 Phone #{ lead.phone }
    .span2 Email: #{ lead.email }
    .span2 Zip Code: #{ lead.zip }
    .span2 Interest: #{ lead.interest }
    / - if current_user.admin? && !current_user?(user)
    /   #delete.span1.offset1= link_to "&times;".html_safe, user, method: :delete, data: { confirm: "Delete User?" }, class: 'close'
%li.divider

app/views/leads/_leads.html.haml
- @leads.each do |lead|
  - @id = lead.id.to_s
  / - @activity = lead.activities ? lead.activities.order('created_at DESC').first : nil
  %li.lead-item{:id => "lead_"+@id, :class => lead_staleness(lead)}
    .row-fluid.lead-data{:id => "leaddata_"+@id}
      .span1.lead-id=       lead_badge(lead.id, lead.status)
      .span2.lead-name=     link_to lead.name, lead
      .span2.lead-phone=    phone_format(lead.phone)
      / .span1.lead-phone=    lead.phone
      .span2.lead-email=    lead.email
      .span1.lead-zip=      lead.zip
      .span1.lead-interest= lead.interest
      .span2.lead-status=   lead.status
      / .span1
      /   %strong.updated-at= l(lead.updated_at, format: :short)
      .span1
        %button{ :class => "btn-edit btn btn-mini btn-primary" }
          #{ icon("icon-edit icon-white") }
    = simple_form_for(lead, :defaults => { :required => false }, :html => { :class => 'form-vertical' }, remote: true) do |f|
      = f.error_notification
      .row-fluid.error-placeholder
      .row-fluid.lead-form{:id => "leadform_"+@id}
        .span1
          %strong ##{ lead.id }
          %small.row-fluid.muted Created On:
          %strong.muted= l(lead.created_at, format: :short)
        .span2= f.input :name, placeholder: 'First Last', input_html: { pattern: "[a-zA-Z-. ]+", id: nil }
        .span2= f.input :phone, placeholder: '123-456-7890', input_html: { pattern: "[(]?[0-9]{3}[)]?[-. ]?[0-9]{3}[-. ]?[0-9]{4}", id: nil }
        / .span1= f.input :phone, placeholder: '123-456-7890', input_html: { pattern: "[(]?[0-9]{3}[)]?[-. ]?[0-9]{3}[-. ]?[0-9]{4}", id: nil }
        .span2= f.input :email, placeholder: 'user@example.com', input_html: { id: nil }
        .span1= f.input :zip, placeholder: '12345', input_html: { pattern: "[0-9]{5}", id: nil }
        .span1= f.input :interest, :label => false, :collection => lead_interests, :as => :radio_buttons, input_html: { id: nil }
        .span2
          = f.input :status, :label => false, :collection => lead_status_options, :include_blank => false, input_html: { id: nil }
          = f.input :notes, input_html: { :class => "small", id: nil }
          / - if @activity
          /   %small.muted Recent Activity:
          /   %small
          /     = link_to @activity.owner.name, {:controller => "users", :action => "show", :id => @activity.owner.id } if @activity.owner
          /     #{ @activity.key.gsub('lead.', '') }d
          /     = link_to time_ago_in_words(@activity.created_at), {:controller => "activities", :action => "show", :id => @activity.id }
          /     ago
          / - else
          / %small.row-fluid.muted Last Updated:
          / %strong.updated-at= l(lead.updated_at, format: :short)
        .span1
          %button{ :class => "btn-collapse btn btn-mini btn-success" }
            #{ icon("icon-check icon-white") }
          = f.button :submit, "Update", :disabled => true, :class => "btn-action btn-update", :id => nil#, data: {disable_with: "Saving..."}
          = button_link_to "Delete", lead_path(lead), :class => "btn btn-action btn-danger", :id => nil, :remote => true, :method => :delete, :data => { :confirm => 'Delete "'+lead.name+'" permanently?' }
        / - if current_user.admin? && !current_user?(user)
        /   #delete.span1.offset1= link_to "&times;".html_safe, user, method: :delete, data: { confirm: "Delete User?" }, class: 'close'
      .row-fluid.divider

app/views/leads/errors.html.haml
%h1.center Please review your information

%h3.center
  There were some missing fields and/or errors in the information you provided.  Please check and submit again.

%hr

.row
  .span4.offset4
    = render 'leads/form'

%hr

app/views/leads/index.html.haml
.row-fluid
  %h2
    All Leads

.label.label-info= page_entries_info @leads
#lead-controls.row-fluid
  = will_paginate @leads, :class => 'pagination', :previous_label => icon("icon-chevron-left", true), :next_label => icon("icon-chevron-right", true), :inner_window => 2, :outer_window => 0
  = form_tag @lead, :class => "navbar-search pull-right", :method => :get do
    = text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search Leads"
  .lead-links.pull-right
    = lead_badge(lead_status_link("New Lead"), "New Lead")
    = lead_badge(lead_status_link("Voicemail Left"), "Voicemail Left")
    = lead_badge(lead_status_link("Non-Responsive"), "Non-Responsive")
    = lead_badge(lead_status_link("Appointment Set"), "Appointment Set")
    = lead_badge(lead_status_link("Job Sold"), "Job Sold")


%ul.nav.nav-list.table-striped
  %li#leads_header
    .navbar
      .navbar-inner
        .row-fluid
          .span1= sortable "created_at", "Lead"
          .span2= sortable "name"
          .span2= sortable "phone"
          / .span1= sortable "phone"
          .span2= sortable "email"
          .span1= sortable "zip", "Zip Code"
          .span1= sortable "interest"
          .span2= sortable "status"
          / .span1= sortable "updated_at", "Updates"
          .span1 <span>Actions</span>

  = render 'leads/leads'

app/views/leads/new.html.haml
%h1.center Get a FREE Quote!

/ %h3.center
/   There were some missing fields and/or errors in the information you provided.  Please check and submit again.

%hr

.row
  .span4.offset4
    = render 'leads/form'

%hr

app/views/leads/show.html.haml
- provide(:title, @lead.name)
%h1= @lead.name.titleize
.center.hero-unit
  %ul.nav.nav-list
    %li.nav-header User Info
    %li.divider
    %li
      .row-fluid
        .span4 Lead: #{ @lead.name }
        .span4 Email: #{ @lead.email }
    %li.divider

- unless @activities.empty?
  %h3 Recent Activities performed on #{ @lead.name.titleize }

  = will_paginate @activities, :class => 'pagination', :previous_label => icon("icon-chevron-left", true), :next_label => icon("icon-chevron-right", true)
  %ul.nav.nav-list
    - @activities.each do |activity|
      .activity
        = render_activity activity

app/views/leads/sorry.html.haml
- provide(:title, 'Out of Area')

%h1.center We're sorry, your location is outside our service area.

%h3.center
  DoorsNWindows primarily serves Greater Los Angeles and Inland Empire locations.
  We regret to inform you that your location is outside our service area.

%hr